import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Head from 'next/head';

const bonheurRoyale = localFont({
	src: './fonts/BonheurRoyale-Regular.ttf',
	variable: '--font-bonheur-royale',
	weight: '400',
});

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Head>
				<link
					href='https://fonts.googleapis.com/css2?family=Bonheur+Royale&display=swap'
					rel='stylesheet'
				/>
			</Head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${bonheurRoyale.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
